title: Heidi's Favorite Things
author: Heidi
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  A place to list things.

# social links
github_username:  heidi-work

show_excerpts: true # set to false to remove excerpts on the homepage
